#!/bin/bash

if [[ $# -eq 0 ]]
then
        echo "Missing options!"
        echo "(run $0 -h for help)"
        echo ""
        exit 0
fi

RECURSION="false"
LOWERIZE="false"
UPPERIZE="false"
HELP="false"
while getopts "hrlu" OPTION; do
        case $OPTION in
                r)
			RECURSION="true"
                        ;;
		l)
			LOWERIZE="true"
                        ;;
		u)
			UPPERIZE="true"
                        ;;
                h)
			HELP="true"
                        ;;
        esac
done
if [[ $LOWERIZE = "true" && $UPPERIZE = "true" ]]
then
	echo " Cannot use both -l and -u at the same time"
	exit 0
fi

if [[ $HELP = "true" ]]
then
	if [[ $LOWERIZE = "true" || $UPPERIZE = "true" ]]
	then
		echo "Wrong syntax, cannot use -l or -u with -h"
		exit 0
	fi
	
	echo "Usage:"
        echo "$0 -h"
	echo "$0 -r -l <directory> "
	echo "$0 -r -u <directory> "
        echo "$0 -l <directory> "		
	echo "$0 -u <directory> "
	echo "$0 <sed pattern> <directory>"
	echo "$0 -r <sed pattern> <directory>"
        echo ""
	echo "   -r     to use recursion"
        echo "   -l     to lowercase all files and directories in given directory"
	echo "   -u     to uppercase all files and directories in given directory"
        echo "   -h     help (this output)"
	echo "   A sed pattern can also be used insted of [-l|-u]"
        exit 0

fi

if [[ $LOWERIZE = "true" ]]
then
	SED_PATTERN="s/\(.*\)/\L\1/"
else
	if [[ $UPPERIZE = "true" ]]
	then
		SED_PATTERN="s/\(.*\)/\U\1/"
	else
		if [[ $RECURSION = "true" ]]
		then
			SED_PATTERN=$2
		else
			SED_PATTERN=$1
		fi
	fi
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
if [[ $RECURSION = "true" ]]
then
	for ITEM in `find $3 -depth`
	do
		mv "$ITEM" "`dirname "${ITEM}"`/$(echo -n `basename "$ITEM"` | sed -e "$SED_PATTERN")" 2> /dev/null
	done
else
	for ITEM in `find $2 -depth -maxdepth 1`
	do
		mv "$ITEM" "`dirname "${ITEM}"`/$(echo -n `basename "$ITEM"` | sed -e "$SED_PATTERN")" 2> /dev/null
	done
	
fi
IFS=$SAVEIFS
